src/Entity/Article.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use App\Form\Constraint as Assert;

/**
 * Category.
 *
 * Category are articles parents
 *
 * @ORM\Table(name="cms_article")
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 * @ORM\HasLifecycleCallbacks()
 *
 * @Assert\Publication()
 */
class Article
{
    const PUBLICATION_STATUS_DRAFT = 0;
    const PUBLICATION_STATUS_VALIDATION = 1;
    const PUBLICATION_STATUS_PUBLISHED = 2;

    /**
     * Entity id.
     *
     * @var string
     *
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * Article title.
     *
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    protected $title;

    /**
     * Article canonical url.
     *
     * @var string
     *
     * @ORM\Column(name="canonical", type="string", nullable=true)
     */
    protected $canonical;

    /**
     * Article current status for publication (draft, published...).
     *
     * @var int
     *
     * @ORM\Column(name="publication_status", type="smallint")
     */
    protected $publicationStatus;

    /**
     * Article publication date.
     *
     * @var DateTime
     *
     * @ORM\Column(name="publication_date", type="datetime", nullable=true)
     */
    protected $publicationDate;

    /**
     * Article content.
     *
     * @var string
     *
     * @ORM\Column(name="content", type="text", nullable=true)
     */
    protected $content;

    /**
     * @var Category
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="articles", fetch="EAGER")
     * @ORM\JoinColumn(nullable=true)
     */
    protected $category;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="articles")
     */
    protected $author;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="article")
     * @ORM\JoinColumn(nullable=true)
     */
    protected $comments;

    /**
     * @var bool
     *
     * @ORM\Column(name="is_commentable", type="boolean")
     */
    protected $isCommentable = true;

    /**
     * @var string
     *
     * @Gedmo\Slug(fields={"title"})
     *
     * @ORM\Column(name="slug", type="string", length=255)
     */
    protected $slug;

    /**
     * @var Tag[]|Collection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", mappedBy="articles", cascade={"persist", "remove"})
     */
    protected $tags;

    /**
     * @var DateTime
     *
     * @ORM\Column(name="created_at", type="datetime")
     */
    protected $createdAt;

    /**
     * @var DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     */
    protected $updatedAt;

    /**
     * @var MediaInterface
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Media")
     * @ORM\JoinColumn(nullable=true, onDelete="SET NULL")
     */
    protected $thumbnail;

    /**
     * Article constructor.
     */
    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->title;
    }

    /**
     * @ORM\PrePersist()
     */
    public function setCreatedAt()
    {
        if (!$this->createdAt) {
            $this->createdAt = new DateTime();
        }
    }

    /**
     * Created at cannot be set. But in some case (like imports...), it is required to set created at. Use this method
     * in this case.
     *
     * @param DateTime $createdAt
     */
    public function forceCreatedAt(DateTime $createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     *
     * @param null $value
     *
     * @return $this
     */
    public function setUpdatedAt($value = null)
    {
        if ($value instanceof DateTime) {
            $this->updatedAt = $value;
        } else {
            $this->updatedAt = new DateTime();
        }

        return $this;
    }

    /**
     * @return DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Return entity id.
     *
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set entity id.
     *
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param mixed $title
     */
    public function setTitle($title)
    {
        $this->title = $title;
    }

    /**
     * @return string
     */
    public function getCanonical()
    {
        return $this->canonical;
    }

    /**
     * @param string $canonical
     */
    public function setCanonical($canonical)
    {
        $this->canonical = $canonical;
    }

    /**
     * @return mixed
     */
    public function getPublicationStatus()
    {
        return $this->publicationStatus;
    }

    /**
     * @param mixed $publicationStatus
     */
    public function setPublicationStatus($publicationStatus)
    {
        $this->publicationStatus = $publicationStatus;
    }

    /**
     * @return mixed
     */
    public function getPublicationDate()
    {
        return $this->publicationDate;
    }

    /**
     * @param mixed $publicationDate
     */
    public function setPublicationDate($publicationDate)
    {
        $this->publicationDate = $publicationDate;
    }

    /**
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * @param string $content
     */
    public function setContent($content)
    {
        $this->content = $content;
    }

    /**
     * @return mixed
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * @param mixed $author
     */
    public function setAuthor($author)
    {
        $this->author = $author;
    }

    /**
     * @return mixed
     */
    public function getIsCommentable()
    {
        return $this->isCommentable;
    }

    /**
     * @return bool
     */
    public function isCommentable()
    {
        return (bool) $this->isCommentable;
    }

    /**
     * @param mixed $isCommentable
     */
    public function setIsCommentable($isCommentable)
    {
        $this->isCommentable = $isCommentable;
    }

    /**
     * @return mixed
     */
    public function getComments()
    {
        return $this->comments;
    }

    /**
     * @param mixed $comments
     */
    public function setComments($comments)
    {
        $this->comments = $comments;
    }

    /**
     * @param Comment $comment
     */
    public function addComment(Comment $comment)
    {
        $this->comments->add($comment);
    }

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param mixed $slug
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
    }

    /**
     * @return array
     */
    public function getUrlParameters()
    {
        $year = date('Y');
        $month = date('m');
        $slug = $this->slug;

        if (null !== $this->publicationDate) {
            $year = $this->publicationDate->format('Y');
            $month = $this->publicationDate->format('m');
        }

        if (null === $slug) {
            $slug = '__TOKEN__';
        }

        return [
            'year' => $year,
            'month' => $month,
            'slug' => $slug,
        ];
    }

    /**
     * @return Category
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param Category $category
     */
    public function setCategory($category)
    {
        $this->category = $category;
    }

    /**
     * @return Category[]
     */
    public function getCategories()
    {
        $category = $this->category;
        $categories = [
            $category,
        ];

        while ($category->getParent()) {
            $categories[] = $category->getParent();
            $category = $category->getParent();
        }

        return $categories;
    }

    /**
     * @param Tag $tag
     */
    public function addTag(Tag $tag)
    {
        $this->tags->add($tag);
        $tag->addArticle($this);
    }

    /**
     * @param Tag $tag
     *
     * @return bool
     */
    public function hasTag(Tag $tag)
    {
        return $this
            ->tags
            ->contains($tag);
    }

    /**
     * @param Tag[] $tags
     */
    public function setTags($tags)
    {
        foreach ($this->tags as $tag) {
            $tag->removeArticle($this);
        }

        foreach ($tags as $tag) {
            if (!$tag->hasArticle($this)) {
                $tag->addArticle($this);
            }
        }
        $this->tags = $tags;
    }

    /**
     * @return mixed
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * @return MediaInterface
     */
    public function getThumbnail()
    {
        return $this->thumbnail;
    }

    /**
     * @param MediaInterface $thumbnail
     */
    public function setThumbnail(MediaInterface $thumbnail = null)
    {
        $this->thumbnail = $thumbnail;
    }

    public function getYear(): ?string
    {
        if (null === $this->publicationDate) {
            return '';
        }

        return $this->publicationDate->format('Y');
    }

    public function getMonth(): ?string
    {

src/Controller/Article/Show.php
<?php

namespace App\Controller\Article;

use App\Entity\Article;
use App\Factory\CommentFactory;
use App\Form\Type\AddCommentType;
use App\Mailer\Mailer;
use App\Repository\ArticleRepository;
use App\Repository\CommentRepository;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Twig_Environment;

class Show
{
    /**
     * @var Twig_Environment
     */
    private $twig;

    /**
     * @var ArticleRepository
     */
    private $articleRepository;

    /**
     * @var CommentFactory
     */
    private $commentFactory;

    /**
     * @var FormFactoryInterface
     */
    private $formFactory;

    /**
     * @var CommentRepository
     */
    private $commentRepository;

    /**
     * @var Mailer
     */
    private $mailer;

    public function __construct(
        Twig_Environment $twig,
        ArticleRepository $articleRepository,
        CommentRepository $commentRepository,
        CommentFactory $commentFactory,
        FormFactoryInterface $formFactory,
        Mailer $mailer
    ) {
        $this->twig = $twig;
        $this->articleRepository = $articleRepository;
        $this->commentFactory = $commentFactory;
        $this->formFactory = $formFactory;
        $this->commentRepository = $commentRepository;
        $this->mailer = $mailer;
    }

    public function __invoke(Request $request): Response
    {
        /** @var Article $article */
        $article = $this->articleRepository->findOneBy([
            'slug' => $request->get('slug'),
            'publicationStatus' => Article::PUBLICATION_STATUS_PUBLISHED,
        ]);

        if (null === $article) {
            throw new NotFoundHttpException();
        }
        $comment = $this->commentFactory->create($article);
        $form = $this->formFactory->create(AddCommentType::class, $comment);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->commentRepository->save($comment);
            $this->mailer->sendNewCommentMail($comment);
        }
        $content = $this->twig->render('Article/show.html.twig', [
            'article' => $article,
            'commentForm' => $form->createView(),
        ]);

        return new Response($content);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\Comment;
use App\Form\Type\AddCommentType;
use BlueBear\CmsBundle\Finder\Filter\ArticleFilter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * Display an article or a list of filtered articles.
 */
class ArticleController extends Controller
{
    /**
     * @Template(":Article:show.html.twig")
     *
     * @param Request $request
     *
     * @return array|RedirectResponse
     */
    public function showAction(Request $request)
    {
        $filter = new ArticleFilter();
        $filter->handleRequest($request);
        $article = $this
            ->get('bluebear.cms.article_finder')
            ->findOne($filter);

        if (null === $article) {
            throw new NotFoundHttpException('Article not found');
        }
        $comment = new Comment();
        $comment->setArticle($article);
        $commentForm = $this->createForm(AddCommentType::class, $comment);
        $commentForm->handleRequest($request);

        if ($commentForm->isValid()) {
            // save the new Comment
            $this
                ->get('jk.cms.comment_repository')
                ->save($comment);

            // notify older Comments authors
            $this
                ->get('cms.comment.comment_mailer')
                ->sendNewCommentMail($comment);

            // redirect to the new Comment
            $url = $this->generateUrl(
                'lecomptoir.article.show',
                    $article->getUrlParameters()
                ).'#comment-'.$comment->getId();

            return $this->redirect($url);
        }

        return [
            'article' => $article,
            'commentForm' => $commentForm->createView(),
        ];
    }

    /**
     * @Template(":Article:filter.html.twig")
     *
     * @param Request $request
     *
     * @return array
     */
    public function filterAction(Request $request)
    {
        $filter = new ArticleFilter();
        $filter->handleRequest($request);
        $pager = $this
            ->get('bluebear.cms.article_finder')
            ->find($filter)
        ;

        return [
            'articles' => $pager->getCurrentPageResults(),
            'pager' => $pager,
            'filter' => $filter,
            // title is dynamic in filter action
            'title' => $this->getFilterTitle($filter),
        ];
    }

    /**
     * @Template(":Article:preview.html.twig")
     *
     * @param Article $article
     *
     * @return array
     */
    public function previewAction(Article $article)
    {
        $this->denyAccessUnlessGranted('ROLE_USER');

        return [
            'article' => $article,
        ];
    }

    /**
     * Remove subscriptions for an User and an Article.
     *
     * @param string $slug
     * @param string $email
     *
     * @return RedirectResponse
     */
    public function unsubscribeAction($slug, $email)
    {
        $this
            ->get('jk.cms.comment_repository')
            ->unsubscribe($slug, $email);
        $this
            ->addFlash('success', $this->get('translator')->trans('cms.comment.unsubscribe_success'));

        return $this->redirectToRoute('lecomptoir.homepage');
    }

    /**
     * @param ArticleFilter $filter
     *
     * @return string
     */
    protected function getFilterTitle(ArticleFilter $filter)
    {
        $parameters = $filter->getParameters();
        $title = implode(',', $parameters->all());

        if ($parameters->has('categorySlug')) {
            $category = $this
                ->get('jk.cms.category_repository')
                ->findOneBy([
                    'slug' => $parameters->get('categorySlug'),
                ]);

            if (null === $category) {
                throw new NotFoundHttpException();
            }
            $title = $category->getName();
        }

        return $title;
    }
}

templates/Article/filter.html.twig
{% extends '::layout.html.twig' %}

{% block content %}
    <div class="col-lg-9 col-sm-9 col-sm-9 page filter-article">
        <h2>{{ title | capitalize }}</h2>

        <div class="row">
            {% for article in articles %}
                {% set categoryUrl = path('lecomptoir.article.list_by_category', {categorySlug: article.category.slug}) %}
                {% set categoryLinkTitle = 'lecomptoir.article.go_to_category' | trans({'%category%': article.category.name}) %}
                {% set articleUrl = path('lecomptoir.article.show', article.urlParameters) %}
                {% set articleLinkTitle = 'lecomptoir.article.go_to_read' | trans({'%article%': article.title}) %}

                <div class="col-md-12 article-item">
                    {# Category ribbon #}
                    <h2 class="ribbon">
                        <a href="{{ categoryUrl }}" title="{{ categoryLinkTitle }}">
                            {{ article.category.name }}
                        </a>
                    </h2>

                    {# Article thumbnail #}
                    {% if article.thumbnail %}
                        <a href="{{ articleUrl }}" title="{{ articleLinkTitle }}">
                            <img src="{{ cms_media_path(article.thumbnail) }}"
                                 alt="{{ articleLinkTitle }}"
                                 title="{{ articleLinkTitle }}"/>
                        </a>
                    {% endif %}

                    {# Article publication date#}
                    <span class="title-date">{{ article.publicationDate | localizeddate('full', 'none') }}</span>

                    {# Article title #}
                    <h3>
                        <a href="{{ articleUrl }}" title="{{ articleLinkTitle }}">{{ article.title }}</a>
                    </h3>
                    {# Article truncated content #}
                    <p>{{ article.content | striptags | truncate(500) | raw }}
                        <a href="{{ articleUrl }}" title="{{ articleLinkTitle }}" class="more-link">
                            {{ 'lecomptoir.interface.more_link' | trans }}
                            <i class="fa fa-plus-circle"></i>
                        </a>
                    </p>
                </div>

            {% else %}
                <div class="col-md-12">
                    {{ 'lecomptoir.article.no_result' | trans }}
                </div>
            {% endfor %}
        </div>

        {% if articles | length > 0 %}
            <div class="pager">

                {% if pager.haveToPaginate %}
                    {{ pagerfanta(pager, 'default_translated', {page: pager.currentPage}) }}
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/Article/preview.html.twig
{% extends '::layout.html.twig' %}

{% block title %}{{ article.title }}{% endblock %}

{% block content %}
    <div class="main-content col-lg-9 col-sm-9 col-sm-9 article">
        <div class="article-header">
            <div class="article-title">
                <span class="title-date">{{ article.publicationDate | localizeddate('full', 'none') }}</span>

                <a href="{{ path('lecomptoir.article.list_by_category', {categorySlug: article.category.slug}) }}"
                   title="{{ article.category.slug }}">
                    <span class="ribbon category-ribbon">{{ article.category.name }}</span></a>
                <h2>{{ article.title }}</h2>
            </div>
            <div class="article-thumbnail">
                {% if article.thumbnailFile.filepath is defined %}
                    {{ article.thumbnailFile.filepath }}
                {% endif %}
            </div>
        </div>
        <div class="article-content">
            {{ article.content | raw }}
        </div>
        <div class="article-footer">
            <ul>
                <li id="category-link">
                    <strong>{{ 'lecomptoir.interface.categories' | trans }} :</strong>
                    <a href="{{ path('lecomptoir.article.list_by_category', {categorySlug: article.category.slug}) }}">
                        {{ article.category.name }}
                    </a>
                </li>

                {% if article.tags | length > 0 %}
                    <li>
                        <strong>{{ 'lecomptoir.tags' | trans }} :</strong>
                        <ul class="inline">
                            {% for tag in article.tags %}
                                <li class="tag">
                                    <a href="{{ path('lecomptoir.article.list_by_tag', {tagSlug: tag.slug}) }}">{{ tag.name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock %}

templates/Article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ article.title }}{% endblock %}

{% block content %}
    <div class="main-content col-lg-9 col-sm-9 col-sm-9 article">
        <div class="article-header">
            <div class="article-title">
                <span class="title-date">{{ article.publicationDate | localizeddate('full', 'none') }}</span>

                <a href="{{ path('lecomptoir.article.list_by_category', {categorySlug: article.category.slug}) }}"
                   title="{{ article.category.slug }}">
                    <span class="ribbon category-ribbon">{{ article.category.name }}</span></a>
                <h2>{{ article.title }}</h2>
            </div>
        </div>
        <div class="article-content">
            {{ article.content | raw }}
        </div>
        <div class="article-footer">
            <ul>
                <li id="category-link">
                    <strong>{{ 'lecomptoir.interface.categories' | trans }} :</strong>
                    <a href="{{ path('lecomptoir.article.list_by_category', {categorySlug: article.category.slug}) }}">
                        {{ article.category.name }}
                    </a>
                </li>

                {% if article.tags | length > 0 %}
                    <li>
                        <strong>{{ 'lecomptoir.tags' | trans }} :</strong>
                        <ul class="inline">
                            {% for tag in article.tags %}
                                <li class="tag">
                                    <a href="{{ path('lecomptoir.article.list_by_tag', {tagSlug: tag.slug}) }}">{{ tag.name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endif %}
            </ul>

            {# Article comments (if allowed) #}
            {% if article.isCommentable %}
                <div class="article-comments">
                    <h3 id="add-comment-title">N'hésitez pas à commenter cet article !</h3>

                    {% for comment in article.comments %}
                        <div class="comment">
                            <p class="title" id="comment-{{ comment.id }}">Par {{ comment.authorName }},
                                le {{ comment.createdAt | localizeddate('full', 'none') }}
                                à  {{ comment.createdAt | localizeddate('none', 'short') }}
                            </p>
                            <p class="">{{ comment.content | truncate(500, '...') }}</p>
                        </div>
                    {% endfor %}

                    {# Add comment form #}
                    <form action="" method="post">
                        {{ form_row(commentForm) }}

                        <input type="submit" value="Poster un commentaire" class="btn btn-info comments-btn"/>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}